### ISSUE TITLE
Checklist of criteria - Category 4: Define an application protocol

### ISSUE THREAD

**Issue by maellemelody** [Dylan-Langumier/DAI-Practical-Work-2#10]
### Category 4 - Define an application protocol
- [ ] The repository contains the application protocol that describes your network application
- [ ] The application protocol defines the overview of the network application
- [ ] The application protocol defines the transport protocol(s) the network application uses
- [ ] The application protocol defines the available messages/actions/commands for the client/server to communicate
- [ ] The application protocol defines the success/error codes and their explanations
- [ ] The application protocol is described using successful and unsuccessful examples with one or multiple diagrams
