### ISSUE TITLE
Checklist of criteria - Category 5: Java TCP/UDP programming

### ISSUE THREAD

**Issue by maellemelody** [Dylan-Langumier/DAI-Practical-Work-2#11]
### Category 5 - Java TCP/UDP programming
- [x] The server starts/listens on the defined port(s) by default (you must be able to change it if needed)
- [x] The client accesses the server on a given host (you must be able to change it)
- [x] The client accesses the server on the defined port(s) by default (you must be able to change it if needed)
- [x] The client and server exchange messages/actions/commands to interact with each other
- [x] The client and server correctly process the messages/actions/commands and with their edge-cases in case a problem occurs
- [x] The client and server are compatible across operating systems/languages
- [x] The client and server correctly manage resources in case a problem occurs
