### ISSUE TITLE
Checklist of Criteria - Category 1: Git, GitHub and Markdown 

### ISSUE THREAD

**Issue by maellemelody** [Dylan-Langumier/DAI-Practical-Work-2#8]
### Category 1 - Git, GitHub and Markdown
- [ ] The README is well structured and explains the purpose of your network application so new users can understand it
- [ ] The README explains how to use your network application with examples and outputs so a new user/developer can understand your network application without having to run it locally
- [ ] The README describes explicit commands to clone and build your network application with Git and Maven so new developers can start and develop your project on their own computer
