### ISSUE TITLE
Checklist of criteria - Category 3 : Docker and Docker Compose

### ISSUE THREAD

**Issue by maellemelody** [Dylan-Langumier/DAI-Practical-Work-2#9]
### Category 3 - Docker and Docker Compose
- [x] The network application is packaged and published to GitHub Container Registry with Docker so other people can use your network application with Docker
- [x] The README describes explicit commands to build and publish your network application with Docker
- [x] The README explains how to use your network application with Docker (`docker run` is enough for this practical work, no need to use Docker Compose)
